export const labs = [
  {
    id: "number-line-lab",
    title: "整数の数直線",
    short: "数直線",
    category: "整数・不等式",
    lessonIds: ["integers-signs", "absolute-value", "integer-rules", "linear-inequalities", "absolute-value-equations"],
    practiceIds: ["integer", "absolute-value", "inequality"],
    objectIntro: "数直線の上を右・左へ進む矢印として見る",
    observe: "始点と移動量が決まると、終点が一つに決まる",
    starterExample: "例：はじめの数を \\(-3\\)、もう一つの数を \\(5\\)、操作を引き算にして、\\(-3-5=-8\\) となる左向きの矢印を見る。",
  },
  {
    id: "inequality-lab",
    title: "不等号の向き",
    short: "不等号",
    category: "整数・不等式",
    lessonIds: ["linear-inequalities"],
    practiceIds: ["inequality"],
    objectIntro: "二つの数の位置を比べ、かける数を変えて見る",
    observe: "負の数をかけると、二つの数の左右関係が反対になる",
    starterExample: "例：\\(2<5\\) に \\(-1\\) をかける。\\(-2\\) は \\(-5\\) より右にあるので、\\(-2>-5\\) になる。",
  },
  {
    id: "distribution-lab",
    title: "分配法則の面積モデル",
    short: "分配法則",
    category: "計算ルール",
    lessonIds: ["distribution-numbers", "distribution-letters"],
    practiceIds: ["distribute", "expansion", "factoring"],
    objectIntro: "長方形を二つの色の面積に分けて見る",
    observe: "分けて計算しても、全体の面積は変わらない",
    starterExample: "例：高さを \\(6\\)、幅を \\(10\\) と \\(3\\) にする。\\(6\\times13\\) と \\(6\\times10+6\\times3\\) がどちらも \\(78\\) になる。",
  },
  {
    id: "radical-lab",
    title: "平方根を整理する",
    short: "平方根",
    category: "ルート",
    lessonIds: ["powers-roots", "simplify-roots", "root-operations"],
    practiceIds: ["square-root-meaning", "radical", "root-operations"],
    objectIntro: "同じ大きさの正方形を見つけて、√の外へ出す",
    observe: "平方数の部分だけが、同じ数として外へ出せる",
    starterExample: "例：\\(n=72\\) にして、\\(36\\) の正方形が \\(2\\) 組あることから \\(\\sqrt{72}=6\\sqrt2\\) を確かめる。",
  },
  {
    id: "term-lab",
    title: "同類項をまとめる",
    short: "同類項",
    category: "文字式",
    lessonIds: ["letters-as-boxes", "like-terms", "distribution-letters", "root-operations"],
    practiceIds: ["substitution", "combine", "distribute", "root-operations"],
    objectIntro: "xカードと1カードを別の列に並べる",
    observe: "同じ種類だけがまとまり、反対カード一組は0になる",
    starterExample: "例：たす \\(x\\) カードを \\(5\\) 枚、ひく \\(x\\) カードを \\(2\\) 枚にして、\\(3x\\) が残ることを見る。",
  },
  {
    id: "equation-lab",
    title: "一次方程式のブロックモデル",
    short: "方程式",
    category: "方程式",
    lessonIds: ["identities-equations", "linear-equations", "equation-modeling"],
    practiceIds: ["identities", "equation"],
    objectIntro: "x袋と1ブロックを左右同時に動かす",
    observe: "左右に同じ操作をしても、つり合いは変わらない",
    starterExample: "例：\\(x\\) 袋を \\(3\\) 個、中身を \\(4\\)、左の1ブロックを \\(2\\) 個にして、左右から同じブロックを取る。",
  },
  {
    id: "function-lab",
    title: "関数グラフ",
    short: "関数",
    category: "関数",
    lessonIds: ["functions", "simultaneous-equations"],
    practiceIds: ["function-values", "quadratic", "equation"],
    objectIntro: "xを入れるとyが出る入力マシンとして見る",
    observe: "係数を変えるとグラフの傾き・位置・開き方が変わる",
    starterExample: "例：一次関数を選び、係数を \\(1\\) と \\(2\\) にして、\\(y=x+2\\) の線を見る。",
  },
  {
    id: "quadratic-lab",
    title: "二次関数の頂点",
    short: "二次関数",
    category: "数I・二次関数",
    lessonIds: ["quadratic-vertex", "quadratic-inequalities"],
    practiceIds: ["quadratic", "quadratic-solve", "quadratic-sign"],
    objectIntro: "放物線のいちばん高い・低い場所を先に見る",
    observe: "aの符号と頂点の位置が最大・最小を決める",
    starterExample: "例：開きを \\(1\\)、横位置を \\(2\\)、高さを \\(-3\\) にして、頂点 \\((2,-3)\\) を読む。",
  },
  {
    id: "trig-lab",
    title: "三角比",
    short: "三角比",
    category: "数I・図形と計量",
    lessonIds: ["trig-ratios", "trig-extension", "sine-cosine-rule", "geometry"],
    practiceIds: ["trig", "trig-survey", "sine-cosine-rule", "geometry-basics"],
    objectIntro: "直角三角形の辺の比に色をつけて見る。角度と、好きな1辺の長さを決められる",
    observe: "形が同じなら、拡大しても辺の比は変わらない",
    starterExample: "例：角度を \\(30^\\circ\\)、斜辺を \\(2\\) に決めると、対辺はちょうど \\(1\\)。三角定規の比 \\(1:2:\\sqrt3\\) が目の前に現れる。",
  },
  {
    id: "unit-semicircle-lab",
    title: "単位半円の三角比",
    short: "単位半円",
    category: "数I・図形と計量",
    lessonIds: ["trig-extension", "trig-ratios", "sine-cosine-rule"],
    practiceIds: ["sine-cosine-rule", "trig"],
    objectIntro: "半径1の半円の上で、角 θ の方向にある点の座標を見る",
    observe: "90°を超えると点が y 軸の左へ移り、cos θ（x 座標）だけが負になる",
    starterExample: "例：\\(\\theta\\) を \\(120^\\circ\\) にすると点の座標は \\((-0.5,\\ 0.87)\\)。\\(60^\\circ\\) の点と左右対称で、\\(\\cos\\) の符号だけが変わる。",
  },
  {
    id: "probability-lab",
    title: "確率の木",
    short: "確率",
    category: "数A・確率",
    lessonIds: ["counting-principles", "permutations", "combinations", "probability-a", "data"],
    practiceIds: ["counting", "perm-comb", "probability"],
    objectIntro: "玉の袋から取り出す順番を枝にする",
    observe: "戻す・戻さないで、二回目の分母が変わる",
    starterExample: "例：赤玉を \\(3\\) 個、青玉を \\(5\\) 個にして、「戻さず2回」に切り替え、二回目の全体が \\(7\\) 個になることを見る。",
  },
  {
    id: "lattice-path-lab",
    title: "格子の道の最短経路",
    short: "最短経路",
    category: "数A・場合の数",
    lessonIds: ["combinations-repetition", "combinations", "permutations"],
    practiceIds: ["counting", "perm-comb"],
    objectIntro: "碁盤の目の道を、右と上の矢印の列に置き換えて見る",
    observe: "どの道順も「→ と ↑ の並べ方」とちょうど1対1に対応する",
    starterExample: "例：右へ \\(4\\)・上へ \\(3\\) にすると、道順は \\(\\dfrac{7!}{4!\\,3!}={}_7C_3=35\\) 通り。「別の道順にする」を押すと、対応する矢印の列も一緒に変わる。",
  },
  {
    id: "set-sort-lab",
    title: "数カードを集合に分ける",
    short: "集合",
    category: "数I・集合と命題",
    lessonIds: ["sets-propositions", "venn-diagrams"],
    practiceIds: ["sets"],
    objectIntro: "1から12までの数カードを、条件に合う箱へ分ける",
    observe: "共通部分は両方の条件に合うカード、和集合は少なくとも一方に合うカード",
    starterExample: "例：偶数の集合 \\(A\\) と3の倍数の集合 \\(B\\) で共通部分を選び、\\(6\\) と \\(12\\) が両方の箱に入ることを見る。",
  },
  {
    id: "triangle-angle-lab",
    title: "三角形の内角と外角",
    short: "三角形の角",
    category: "図形の基本",
    lessonIds: ["geometry", "parallel-lines-angles", "geometry-proofs", "geometry-a"],
    practiceIds: ["geometry-basics", "geometry-properties"],
    objectIntro: "三角形の頂点を左右・上下に動かして、3つの角の変化を見る",
    observe: "形をどれだけ変えても、内角の和はいつも180°のまま",
    starterExample: "例：頂点を右へ寄せると角Aと角Bは変わるが、3つの角の和は \\(180^\\circ\\) のまま。外角は、隣り合わない2つの内角の和になる。",
  },
  {
    id: "venn-lab",
    title: "ベン図で人数を数える",
    short: "ベン図",
    category: "数I・集合と命題",
    lessonIds: ["venn-diagrams", "sets-propositions", "counting-principles"],
    practiceIds: ["venn-count", "sets", "counting"],
    objectIntro: "2つの円の人数と重なりを動かして、二重に数えられる部分を見る",
    observe: "そのまま足すと重なりを2回数える。1回分引くと正しい人数になる",
    starterExample: "例：\\(n(A)=18\\)、\\(n(B)=14\\)、重なりを \\(6\\) にすると、\\(n(A\\cup B)=18+14-6=26\\) 人と数えられる。",
  },
  {
    id: "geometry-properties-lab",
    title: "同じ弧を見る円周角",
    short: "円周角",
    category: "数A・図形の性質",
    lessonIds: ["geometry-a", "geometry"],
    practiceIds: ["geometry-properties", "geometry-basics"],
    objectIntro: "円周上の観察点から、同じ弧の両端へ2本の線を結ぶ",
    observe: "観察点を同じ側の弧の上で動かしても、同じ弧を見込む円周角は変わらない",
    starterExample: "例：点 \\(B\\) を円周の下側で動かし、点 \\(D\\) と場所が違っても \\(\\angle ABC=\\angle ADC=60^\\circ\\) のままであることを見る。",
  },
  {
    id: "euclidean-algorithm-lab",
    title: "長方形を正方形で分ける互除法",
    short: "互除法",
    category: "数A・数学と人間の活動",
    lessonIds: ["math-human-activities"],
    practiceIds: ["number-theory"],
    objectIntro: "2本の長さを、同じ大きさの正方形で余りなく区切れるか試す",
    observe: "大きい数を小さい数で割った余りへ置き換えても、共通の区切り幅は変わらない",
    starterExample: "例：\\(84\\) と \\(30\\) を選び、\\(84=30\\times2+24\\)、\\(30=24\\times1+6\\) と余りを小さくして、最大公約数 \\(6\\) を見つける。",
  },
  {
    id: "loan-balance-lab",
    title: "ローンの返済と利息（単利・複利）",
    short: "返済",
    category: "応用・数と式",
    lessonIds: ["linear-equations", "equation-modeling", "functions", "geometric-sequences"],
    practiceIds: ["equation"],
    objectIntro: "借入額・年率・期間を、元金と利息に分けた棒で見る。単利と複利を切り替えられる",
    observe: "単利は同じ額ずつ、複利は利息が利息を生んで等比数列的に増える",
    starterExample: "例：借入額 \\(60\\) 万円・年率 \\(2\\%\\)・期間 \\(12\\) か月の単利では利息 \\(1.2\\) 万円。複利に切り替えて、期間を延ばすと差が開く。",
  },
  {
    id: "accounting-balance-lab",
    title: "会計の売上・費用・利益",
    short: "会計",
    category: "応用・数と式",
    lessonIds: ["exam-review", "functions"],
    practiceIds: ["distribute"],
    objectIntro: "売上から、品物ごとにかかる費用と固定の費用を引く箱として見る",
    observe: "売る個数を増やすと、売上と品物ごとの費用は同じ個数分だけ変わる",
    starterExample: "例：1個 \\(600\\) 円で \\(8\\) 個売り、1個あたりの費用を \\(300\\) 円、固定の費用を \\(1,000\\) 円にする。売上・費用・利益を順に分けて読む。",
  },
  {
    id: "speed-distance-lab",
    title: "速さ・時間・道のり",
    short: "速さ",
    category: "応用・関数",
    lessonIds: ["functions", "linear-equations", "equation-modeling"],
    practiceIds: ["equation"],
    objectIntro: "同じ速さで進むときの道のりを、時間に応じて伸びるバーで見る",
    observe: "速さが一定なら、道のりは時間に比例して増える",
    starterExample: "例：時速を \\(30\\) km、時間を \\(2\\) 時間にする。道のりは \\(30\\times2=60\\) km と読める。",
  },
  {
    id: "data-spread-lab",
    title: "平均と散らばり",
    short: "散らばり",
    category: "応用・データ",
    lessonIds: ["data", "data-analysis-i"],
    practiceIds: ["data-summary", "data-analysis"],
    objectIntro: "五つの値を数直線上の点として並べ、中心と広がりを一緒に見る",
    observe: "平均が同じでも、値の広がり方は変わる",
    starterExample: "例：中心を \\(60\\)、散らばりを \\(8\\) にする。平均は \\(60\\) のまま、最小と最大の差は \\(16\\) になる。",
  },
  {
    id: "box-plot-lab",
    title: "箱ひげ図と四分位数",
    short: "箱ひげ図",
    category: "応用・データ",
    lessonIds: ["box-plots", "data-analysis-i", "data"],
    practiceIds: ["quartiles", "data-summary"],
    objectIntro: "数直線に並んだ11個のデータと、その真下の箱ひげ図を対応させて見る",
    observe: "箱（Q1〜Q3）には、まん中の約半分のデータが入る",
    starterExample: "例：下側の幅を \\(2\\)、上側の幅を \\(8\\) にすると、箱とひげが右へ長く伸び、分布のかたよりがそのまま箱ひげ図の形になる。",
  },
  {
    id: "sigma-stairs-lab",
    title: "Σの階段：1+2+…+n",
    short: "Σの階段",
    category: "数B・数列",
    lessonIds: ["sigma-notation", "arithmetic-sequences", "sum-and-general-term"],
    practiceIds: ["sequence-sum", "arithmetic-sequence"],
    objectIntro: "1段・2段・…・n段と増える階段の石の数として、和を見る",
    observe: "同じ階段を逆さに重ねると、縦 \\(n+1\\)・横 \\(n\\) の長方形になる",
    starterExample: "例：\\(n=5\\) で「逆さの階段を重ねる」と \\(5\\times6=30\\) 個の長方形。その半分の \\(15\\) が \\(1+2+3+4+5\\) と一致する。",
  },
];

export const labCatalog = Object.fromEntries(labs.map((lab) => [lab.id, lab]));

export const unitLabRefs = {
  "integers-signs": ["number-line-lab"],
  "absolute-value": ["number-line-lab"],
  "integer-rules": ["number-line-lab"],
  "absolute-value-equations": ["number-line-lab", "inequality-lab"],
  "distribution-numbers": ["distribution-lab"],
  "expansion-formulas": ["distribution-lab"],
  factoring: ["distribution-lab", "term-lab"],
  "quadratic-equations": ["quadratic-lab"],
  "powers-roots": ["radical-lab"],
  "simplify-roots": ["radical-lab"],
  "root-operations": ["radical-lab", "term-lab"],
  "letters-as-boxes": ["term-lab"],
  "like-terms": ["term-lab"],
  "distribution-letters": ["distribution-lab", "term-lab"],
  "linear-inequalities": ["inequality-lab", "number-line-lab"],
  "sets-propositions": ["set-sort-lab", "venn-lab"],
  "venn-diagrams": ["venn-lab", "set-sort-lab"],
  "identities-equations": ["equation-lab"],
  "simultaneous-equations": ["function-lab"],
  "quadratic-vertex": ["quadratic-lab"],
  "quadratic-inequalities": ["quadratic-lab"],
  "trig-ratios": ["trig-lab", "unit-semicircle-lab"],
  "trig-extension": ["unit-semicircle-lab", "trig-lab"],
  "sine-cosine-rule": ["trig-lab", "unit-semicircle-lab"],
  "counting-principles": ["probability-lab"],
  permutations: ["probability-lab", "lattice-path-lab"],
  combinations: ["probability-lab", "lattice-path-lab"],
  "combinations-repetition": ["lattice-path-lab", "probability-lab"],
  "probability-a": ["probability-lab"],
  "geometry-a": ["geometry-properties-lab", "triangle-angle-lab"],
  "geometry-proofs": ["triangle-angle-lab"],
  "parallel-lines-angles": ["triangle-angle-lab"],
  "math-human-activities": ["euclidean-algorithm-lab"],
  geometry: ["triangle-angle-lab", "geometry-properties-lab", "trig-lab"],
  "linear-equations": ["equation-lab", "loan-balance-lab", "speed-distance-lab"],
  "equation-modeling": ["equation-lab", "speed-distance-lab", "loan-balance-lab"],
  functions: ["function-lab", "speed-distance-lab", "accounting-balance-lab"],
  "function-notation": ["function-lab"],
  "pythagorean-theorem": ["trig-lab", "geometry-properties-lab"],
  "geometric-series-sum": ["loan-balance-lab"],
  "geometric-sequences": ["loan-balance-lab"],
  "prime-factorization": ["radical-lab", "euclidean-algorithm-lab"],
  similarity: ["trig-lab"],
  "conditional-probability": ["probability-lab"],
  "data-analysis-i": ["data-spread-lab", "box-plot-lab"],
  "box-plots": ["box-plot-lab", "data-spread-lab"],
  "sigma-notation": ["sigma-stairs-lab"],
  "arithmetic-sequences": ["sigma-stairs-lab"],
  "sum-and-general-term": ["sigma-stairs-lab"],
  "complementary-events": ["probability-lab"],
  data: ["data-spread-lab", "probability-lab"],
  "exam-review": ["accounting-balance-lab"],
};
