// 出題の「教材としての設定」。実際の問題生成・採点コードは assets/js/app.js に置く。
import { units } from "./lessons.js";

const rawPracticeCatalog = [
  {
    id: "integer",
    label: "整数の計算",
    lessonIds: ["integers-signs", "integer-rules"],
    labIds: ["number-line-lab"],
    level: "はじめの一問",
    numberPolicy: "答えが2桁以内",
  },
  {
    id: "absolute-value",
    label: "絶対値",
    lessonIds: ["absolute-value", "absolute-value-equations"],
    labIds: ["number-line-lab"],
    level: "はじめの一問",
    numberPolicy: "1桁の整数から距離を読む",
  },
  {
    id: "exponent",
    label: "指数法則",
    lessonIds: ["exponent-rules"],
    labIds: [],
    level: "はじめの一問",
    numberPolicy: "指数は1桁・回数を数えて確かめられる大きさ",
  },
  {
    id: "arithmetic-sequence",
    label: "等差数列",
    lessonIds: ["arithmetic-sequences"],
    labIds: [],
    level: "はじめの一問",
    numberPolicy: "公差は1桁・項番号は15以下",
  },
  {
    id: "venn-count",
    label: "ベン図の個数",
    lessonIds: ["venn-diagrams"],
    labIds: ["venn-lab"],
    level: "はじめの一問",
    numberPolicy: "全体は40人以下・重なりから順に埋める",
  },
  {
    id: "radical",
    label: "ルート整理",
    lessonIds: ["simplify-roots"],
    labIds: ["radical-lab"],
    level: "はじめの一問",
    numberPolicy: "ルートの中は100未満",
  },
  {
    id: "square-root-meaning",
    label: "平方と平方根",
    lessonIds: ["powers-roots"],
    labIds: ["radical-lab"],
    level: "はじめの一問",
    numberPolicy: "平方数は100以下",
  },
  {
    id: "root-operations",
    label: "ルートの計算",
    lessonIds: ["root-operations"],
    labIds: ["radical-lab", "term-lab"],
    level: "はじめの一問",
    numberPolicy: "係数は一桁・ルートの中は50以下",
  },
  {
    id: "substitution",
    label: "式の値",
    lessonIds: ["letters-as-boxes"],
    labIds: ["term-lab"],
    level: "はじめの一問",
    numberPolicy: "答えが2桁以内",
  },
  {
    id: "combine",
    label: "同類項",
    lessonIds: ["like-terms"],
    labIds: ["term-lab"],
    level: "はじめの一問",
    numberPolicy: "係数は一桁",
  },
  {
    id: "distribute",
    label: "分配法則",
    lessonIds: ["distribution-numbers", "distribution-letters"],
    labIds: ["distribution-lab"],
    level: "はじめの一問",
    numberPolicy: "係数は一桁・定数は2桁以内",
  },
  {
    id: "equation",
    label: "一次方程式",
    lessonIds: ["linear-equations", "equation-modeling"],
    labIds: ["equation-lab"],
    level: "はじめの一問",
    numberPolicy: "途中計算が2桁以内",
  },
  {
    id: "sets",
    label: "集合と命題",
    lessonIds: ["sets-propositions"],
    labIds: ["set-sort-lab"],
    level: "はじめの一問",
    numberPolicy: "1から12までの整数と短い命題",
  },
  {
    id: "identities",
    label: "恒等式と方程式",
    lessonIds: ["identities-equations"],
    labIds: ["equation-lab"],
    level: "はじめの一問",
    numberPolicy: "代入は一桁・展開は一段階",
  },
  {
    id: "inequality",
    label: "一次不等式",
    lessonIds: ["linear-inequalities"],
    labIds: ["inequality-lab", "number-line-lab"],
    level: "基礎を確認",
    numberPolicy: "境目は一桁",
  },
  {
    id: "quadratic",
    label: "二次関数",
    lessonIds: ["quadratic-vertex"],
    labIds: ["quadratic-lab"],
    level: "基礎を確認",
    numberPolicy: "頂点の座標は一桁",
  },
  {
    id: "function-values",
    label: "関数の式と値",
    lessonIds: ["functions"],
    labIds: ["function-lab"],
    level: "はじめの一問",
    numberPolicy: "係数・入力・出力は一桁中心",
  },
  {
    id: "quadratic-sign",
    label: "二次不等式",
    lessonIds: ["quadratic-inequalities"],
    labIds: ["quadratic-lab"],
    level: "はじめの一問",
    numberPolicy: "整数解は一桁・因数分解できる式",
  },
  {
    id: "trig",
    label: "三角比",
    lessonIds: ["trig-ratios"],
    labIds: ["trig-lab"],
    level: "基礎を確認",
    numberPolicy: "3・4・5などの基本比",
  },
  {
    id: "sine-cosine-rule",
    label: "正弦定理・余弦定理",
    lessonIds: ["sine-cosine-rule"],
    labIds: ["trig-lab"],
    level: "はじめの一問",
    numberPolicy: "直角や60度を含む計算しやすい三角形",
  },
  {
    id: "trig-survey",
    label: "三角比で測る",
    lessonIds: ["trig-ratios", "sine-cosine-rule"],
    labIds: ["trig-lab"],
    level: "はじめの一問",
    numberPolicy: "sin30°・cos60°・tan45° など、ちょうどの値になる角だけを使う",
  },
  {
    id: "counting",
    label: "場合の数",
    lessonIds: ["counting-principles"],
    labIds: ["probability-lab"],
    level: "基礎を確認",
    numberPolicy: "答えが2桁以内",
  },
  {
    id: "probability",
    label: "確率",
    lessonIds: ["probability-a"],
    labIds: ["probability-lab"],
    level: "基礎を確認",
    numberPolicy: "玉は合計7個以下を中心",
  },
  {
    id: "data-summary",
    label: "平均・中央値・範囲",
    lessonIds: ["data"],
    labIds: ["data-spread-lab"],
    level: "はじめの一問",
    numberPolicy: "5個以下の並べ替えやすい整数",
  },
  {
    id: "data-analysis",
    label: "分散・標準偏差",
    lessonIds: ["data-analysis-i"],
    labIds: ["data-spread-lab"],
    level: "はじめの一問",
    numberPolicy: "平均・分散・標準偏差が整数になる4個のデータ",
  },
  {
    id: "geometry-properties",
    label: "円と図形の性質",
    lessonIds: ["geometry-a"],
    labIds: ["geometry-properties-lab"],
    level: "はじめの一問",
    numberPolicy: "角度は30度・40度・60度を中心",
  },
  {
    id: "number-theory",
    label: "整数と互除法",
    lessonIds: ["math-human-activities"],
    labIds: ["euclidean-algorithm-lab"],
    level: "はじめの一問",
    numberPolicy: "120以下の整数・余りは3段階以内",
  },
  {
    id: "geometry-basics",
    label: "図形の基本量",
    lessonIds: ["geometry"],
    labIds: ["geometry-properties-lab", "trig-lab"],
    level: "はじめの一問",
    numberPolicy: "三角形の角と3・4・5などの直角三角形",
  },
  {
    id: "expansion",
    label: "展開・乗法公式",
    lessonIds: ["expansion-formulas"],
    labIds: ["distribution-lab"],
    level: "はじめの一問",
    numberPolicy: "(x+a)(x+b) 型・数は1桁",
  },
  {
    id: "factoring",
    label: "因数分解",
    lessonIds: ["factoring"],
    labIds: ["distribution-lab", "term-lab"],
    level: "はじめの一問",
    numberPolicy: "かけて c・たして b の2数さがし（まず正の数から）",
  },
  {
    id: "quadratic-solve",
    label: "二次方程式を解く",
    lessonIds: ["quadratic-equations"],
    labIds: ["quadratic-lab"],
    level: "はじめの一問",
    numberPolicy: "因数分解で解ける形・解は1桁の整数",
  },
  {
    id: "perm-comb",
    label: "順列と組合せ",
    lessonIds: ["permutations", "combinations", "circular-permutations"],
    labIds: ["probability-lab", "lattice-path-lab"],
    level: "はじめの一問",
    numberPolicy: "nは7以下・PとCの値を並べて比べる",
  },
  {
    id: "sequence-sum",
    label: "等比数列とΣ",
    lessonIds: ["geometric-sequences", "sigma-notation", "geometric-series-sum"],
    labIds: ["sigma-stairs-lab"],
    level: "はじめの一問",
    numberPolicy: "公比は2か3・Σは書き出して確かめられる大きさ",
  },
  {
    id: "quartiles",
    label: "四分位数と箱ひげ図",
    lessonIds: ["box-plots"],
    labIds: ["box-plot-lab"],
    level: "はじめの一問",
    numberPolicy: "整列済みの7個のデータから5つの数を読む",
  },
];

const advancedPolicies = {
  integer: "かっこを含む3段階の計算・答えは3桁以内",
  "absolute-value": "積や差の絶対値を、計算してから距離として読む",
  exponent: "累乗の積と商を組み合わせて指数を整理する",
  "arithmetic-sequence": "離れた2つの項から公差を逆算して一般項を使う",
  "venn-count": "『どちらでもない』の人数から重なりを逆算する",
  radical: "ルートの中は1400以下・大きい平方因数（\\(8^2\\)〜\\(14^2\\)）を探す",
  "square-root-meaning": "平方数は400以下・√と方程式の解を区別する",
  "root-operations": "係数は2桁を含む、同じルートの加減",
  substitution: "負の数・2乗を含む式へ代入する",
  combine: "3種類以上の項を符号ごと整理する",
  distribute: "2つのかっこを順に展開する",
  equation: "両辺に文字がある一次方程式",
  sets: "和集合の補集合まで扱い、条件に合わない要素も整理する",
  identities: "係数を比較して恒等式の未知係数を求める",
  inequality: "両辺に文字がある一次不等式",
  quadratic: "平方完成して頂点を求める",
  "function-values": "2点から一次関数の式を決める",
  "quadratic-sign": "2次不等式の向きと根の内外を使い分ける",
  trig: "代表角と辺の長さから未知の辺を求める",
  "trig-survey": "60°の見上げで √3 が残る、木の高さの測量",
  "sine-cosine-rule": "辺と角の対応を自分で選んで定理を使う",
  counting: "重複を除く順列・組合せ",
  probability: "少なくとも1回起こる確率を余事象で求める",
  "data-summary": "未整列の6個のデータから平均・中央値・範囲を順に求める",
  "data-analysis": "偏差が異なるデータの分散を分数で求める",
  "geometry-properties": "円周角から弧・中心角を逆算する",
  "number-theory": "3桁の整数で互除法を4段階以上使う",
  "geometry-basics": "三平方の定理で未知の短辺を求める",
  expansion: "係数つきの (ax+b)(cx+d) を展開する",
  factoring: "定数項が負になる因数分解・2数の符号を見極める",
  "quadratic-solve": "因数分解が見えにくい形を、判別式と解の公式で解く",
  "perm-comb": "円順列と、同じものを含む順列",
  "sequence-sum": "等比数列の和と Σ(2k+m) 型を公式で計算する",
  quartiles: "8個（偶数個）のデータで、真ん中2つの平均が要る四分位数",
};

// 問題の目次は、対応する単元の学習順（learningPath 順）に並べる。
const unitOrder = new Map(units.map((unit) => [unit.id, unit.order]));
const firstLessonOrder = (practice) =>
  Math.min(...practice.lessonIds.map((lessonId) => unitOrder.get(lessonId) ?? Number.MAX_SAFE_INTEGER));

export const practiceCatalog = rawPracticeCatalog
  .map((practice) => ({
    ...practice,
    advancedLevel: "少し進んだ問題",
    advancedPolicy: advancedPolicies[practice.id],
  }))
  .sort((first, second) => firstLessonOrder(first) - firstLessonOrder(second));
